import CodePays from "./CodePays";

const PAYS = [
    { name: 'Allemagne 🇩🇪', code: CodePays.Allemagne },
    { name: 'Algérie 🇩🇿', code: CodePays.Algerie },
    { name: 'Antilles-Guyane 🇬🇫', code: CodePays.AntillesGuyane },
    { name: 'Arabie Saoudite 🇸🇦', code: CodePays.ArabieSaoudite },
    { name: 'Argentine 🇦🇷', code: CodePays.Argentine },
    { name: 'Autriche 🇦🇹', code: CodePays.Autriche },
    { name: 'Australie 🇦🇺', code: CodePays.Australie },
    { name: 'Belgique 🇧🇪', code: CodePays.Belgique },
    { name: 'Bénin 🇧🇯', code: CodePays.Benin },
    { name: 'Bulgarie 🇧🇬', code: CodePays.Bulgarie },
    { name: 'Cameroun 🇨🇲', code: CodePays.Cameroun },
    { name: 'Canada 🇨🇦', code: CodePays.Canada },
    { name: 'Chine 🇨🇳', code: CodePays.Chine },
    { name: 'Chypre 🇨🇾', code: CodePays.Chypre },
    { name: 'Corée du Sud 🇰🇷', code: CodePays.CoreeDuSud },
    { name: 'Croatie 🇭🇷', code: CodePays.Croatie },
    { name: 'Danemark 🇩🇰', code: CodePays.Danemark },
    { name: 'Egypte 🇪🇬', code: CodePays.Egypte },
    { name: 'États-Unis 🇺🇸', code: CodePays.EtatsUnis },
    { name: 'Emirats Arabes Unis 🇦🇪', code: CodePays.EmiratsArabesUnis },
    { name: 'Estonie 🇪🇪', code: CodePays.Estonie },
    { name: 'Espagne 🇪🇸', code: CodePays.Espagne },
    { name: 'Grèce 🇬🇷', code: CodePays.Grece },
    { name: 'Kenya 🇰🇪', code: CodePays.Kenya },
    { name: 'Hongrie 🇭🇺', code: CodePays.Hongrie },
    { name: 'Italie 🇮🇹', code: CodePays.Italie },
    { name: 'Irlande 🇮🇪', code: CodePays.Irlande },
    { name: 'Islande 🇮🇸', code: CodePays.Islande },
    { name: 'Israel 🇮🇱', code: CodePays.Israel },
    { name: 'Japon 🇯🇵', code: CodePays.Japon },
    { name: 'Laos 🇱🇦', code: CodePays.Laos },
    { name: 'La Réunion 🇷🇪', code: CodePays.LaReunion },
    { name: 'Liban 🇱🇧', code: CodePays.Liban },
    { name: 'Luxembourg 🇱🇺', code: CodePays.Luxembourg },
    { name: 'Malte 🇲🇹', code: CodePays.Malte },
    { name: 'Maroc 🇲🇦', code: CodePays.Maroc },
    { name: 'Mayotte 🇾🇹', code: CodePays.Mayotte },
    { name: 'Mexique 🇲🇽', code: CodePays.Mexique },
    { name: 'Myanmar 🇲🇲', code: CodePays.Myanmar },
    { name: 'Nouvelle-Zélande 🇳🇿', code: CodePays.NouvelleZelande },
    { name: 'Norvège 🇳🇴', code: CodePays.Norvege },
    { name: 'Pays-Bas 🇳🇱', code: CodePays.PaysBas },
    { name: 'Portugal 🇵🇹', code: CodePays.Portugal },
    { name: 'Pologne 🇵🇱', code: CodePays.Pologne },
    { name: 'Qatar 🇶🇦', code: CodePays.Qatar },
    { name: 'République Dominicaine 🇩🇴', code: CodePays.RepubliqueDominicaine },
    { name: 'République Tchèque 🇨🇿', code: CodePays.RepubliqueTcheque },
    { name: 'Roumanie 🇷🇴', code: CodePays.Roumanie },
    { name: 'Royaume-Uni 🇬🇧', code: CodePays.RoyaumeUni },
    { name: 'Russie 🇷🇺', code: CodePays.Russie },
    { name: 'Sénégal 🇸🇳', code: CodePays.Senegal },
    { name: 'Serbie 🇷🇸', code: CodePays.Serbie },
    { name: 'Slovaquie 🇸🇰', code: CodePays.Slovaquie },
    { name: 'Slovénie 🇸🇮', code: CodePays.Slovenie },
    { name: 'Suède 🇸🇪', code: CodePays.Suede },
    { name: 'Suisse 🇨🇭', code: CodePays.Suisse },
    { name: 'Thailande 🇹🇭', code: CodePays.Thailande },
    { name: 'Turquie 🇹🇷', code: CodePays.Turquie },
    { name: 'Tunisie 🇹🇳', code: CodePays.Tunisie },
    { name: 'Ukraine 🇺🇦', code: CodePays.Ukraine },
] as const;

export default PAYS;